### ISSUE TITLE
prod.secret.exs missing

### ISSUE THREAD

**Issue by drehak** [FloatingGhost/HallOfMirrors#1]
Inside a freshly cloned repo:

```
# mix deps.get
** (ArgumentError) attempting to load configuration config/prod.secret.exs recursively
    (mix) lib/mix/config.ex:197: Mix.Config.eval_config!/1
    (mix) lib/mix/config.ex:187: anonymous fn/2 in Mix.Config.__import__!/2
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix) lib/mix/config.ex:186: Mix.Config.__import__!/2
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir) lib/code.ex:232: Code.eval_string/3
    (mix) lib/mix/config.ex:187: anonymous fn/2 in Mix.Config.__import__!/2
```

Possibly caused by https://github.com/phoenixframework/phoenix/pull/717.

**Comment by FloatingGhost** [comment]
Just to make sure, you don't have an `import config` line at the bottom of your `prod.secret.exs` or something like that?

**Comment by FloatingGhost** [comment]
Ah, you said fresh

In that case it's probably because it can't find one to load

Try just creating a basic config there with nothing more than `use Mix.Config` in it

**Comment by drehak** [comment]
Done that and installation works now, thanks!

**Comment by drehak** [comment]
Oh wait... it doesn't.

```
Generated hallofmirrors app
** (KeyError) key :database not found in: [telemetry_prefix: [:hallofmirrors, :repo], otp_app: :hallofmirrors, timeout: 15000, pool_size: 10]
    (elixir) lib/keyword.ex:386: Keyword.fetch!/2
    lib/ecto/adapters/postgres.ex:126: Ecto.Adapters.Postgres.storage_up/1
    lib/mix/tasks/ecto.create.ex:53: anonymous fn/3 in Mix.Tasks.Ecto.Create.run/1
    (elixir) lib/enum.ex:765: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:765: Enum.each/2
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/task.ex:350: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:279: Mix.Task.run/2
```

Any idea what this could be caused by?

**Comment by FloatingGhost** [comment]
so `deps.get` doesn't need any specific config, but when you're actually running the thing it needs the entire config

I'll just give you what I use, change as needed
```elixir
use Mix.Config

config :hallofmirrors, HallofmirrorsWeb.Endpoint,
   url: [host: "ihatebeinga.live", scheme: "https", port: 4001],
   http: [port: 4005, ip: {127,0,0,1}]
config :logger, level: :debug


config :extwitter, :oauth, [
   consumer_key: "CHANGEM",
   consumer_secret: "CHANGEME",
   access_token: "CHANGEME",
   access_token_secret: "CHANGEME"
]

config :hallofmirrors, Hallofmirrors.Repo,
  username: "my_user",
  password: "CHANGEME",
  database: "hallofmirrors_prod",
  pool_size: 15
```
