### ISSUE TITLE
No case clause matching

### ISSUE THREAD

**Issue by KaitoCross** [FloatingGhost/HallOfMirrors#9]
Hello :)
I was just testing a fresh install (Arch Linux, latest packages) and got this error when creating a new mirror:

```[debug] Processing with HallofmirrorsWeb.AccountController.create/2
  Parameters: %{"_csrf_token" => "[redacted]", "email" => "[redacted]", "instance_url" => "https://[redacted]", "media_only" => "false", "mirroring" => "[redacted]", "name" => "[redacted]", "password" => "[FILTERED]"}
  Pipelines: [:browser]
[debug] QUERY OK source="instances" db=0.7ms decode=1.0ms queue=1.0ms idle=9771.0ms
SELECT i0."id", i0."url", i0."client_id", i0."client_secret" FROM "instances" AS i0 WHERE (i0."url" = $1) ["https://[redacted]"]
[info] Sent 500 in 170ms
[error] #PID<0.580.0> running HallofmirrorsWeb.Endpoint (connection #PID<0.579.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: POST /accounts/
** (exit) an exception was raised:
    ** (CaseClauseError) no case clause matching: {:error, %HTTPoison.Error{id: nil, reason: {:options, {:sslv3, {:versions, [:"tlsv1.2", :"tlsv1.1", :tlsv1, :sslv3]}}}}}
        (hallofmirrors 0.1.0) lib/hallofmirrors/authenticator.ex:17: Hallofmirrors.Authenticator.create_oauth/1
        (hallofmirrors 0.1.0) lib/hallofmirrors/instance.ex:27: Hallofmirrors.Instance.create/1
        (hallofmirrors 0.1.0) lib/hallofmirrors_web/controllers/account_controller.ex:12: HallofmirrorsWeb.AccountController.create/2
        (hallofmirrors 0.1.0) lib/hallofmirrors_web/controllers/account_controller.ex:1: HallofmirrorsWeb.AccountController.action/2
        (hallofmirrors 0.1.0) lib/hallofmirrors_web/controllers/account_controller.ex:1: HallofmirrorsWeb.AccountController.phoenix_controller_pipeline/2
        (phoenix 1.4.12) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
        (hallofmirrors 0.1.0) lib/hallofmirrors_web/endpoint.ex:1: HallofmirrorsWeb.Endpoint.plug_builder_call/2
        (hallofmirrors 0.1.0) lib/plug/debugger.ex:122: HallofmirrorsWeb.Endpoint."call (overridable 3)"/2
        (hallofmirrors 0.1.0) lib/hallofmirrors_web/endpoint.ex:1: HallofmirrorsWeb.Endpoint.call/2
        (phoenix 1.4.12) lib/phoenix/endpoint/cowboy2_handler.ex:42: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.7.0) /home/dash/programs/HallOfMirrors/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy 2.7.0) /home/dash/programs/HallOfMirrors/deps/cowboy/src/cowboy_stream_h.erl:320: :cowboy_stream_h.execute/3
        (cowboy 2.7.0) /home/dash/programs/HallOfMirrors/deps/cowboy/src/cowboy_stream_h.erl:302: :cowboy_stream_h.request_process/3
        (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

**Comment by FloatingGhost** [comment]
This was an OTP thing that i fixed locally but never pushed

b3a2743 should resolve this

**Comment by KaitoCross** [comment]
Thanks. That fixed the issue.
